services:
  nginx:
    build:
      context: . # Build context is the current directory
      dockerfile: ./nginx/Dockerfile # Optional: If you need a custom Nginx image
    container_name: streamctrl_nginx
    ports:
      - "80:80" # Map host port 80 to container port 80 (where Nginx listens)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Mount your custom Nginx config
    depends_on:
      - frontend # Nginx depends on frontend and backend being available
      - backend

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile # Path to your frontend Dockerfile
    container_name: streamctrl_frontend
    # No ports mapping needed if only Nginx accesses it directly in Docker network
    # You might expose it for local debugging, but not in production for Nginx to handle.
    expose:
      - "5173" # Expose port 5173 to other containers within the Docker network
    environment:
      # Pass environment variables to your React app if needed (e.g., API_BASE_URL)
      # However, for proxied requests, the client-side code will still use relative paths
      NODE_ENV: production
    depends_on:
      - backend # Frontend might depend on backend if it makes direct calls (unlikely with this setup)

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile # Path to your backend Dockerfile
    container_name: streamctrl_backend
    expose:
      - "5468" # Expose port 5468 to other containers
    environment:
      # Any environment variables for your backend
      NODE_ENV: production
    # Add database or other dependencies here
