# File: Dockerfile.nginx
FROM nginx:latest

# Remove the default Nginx configuration file
RUN rm /etc/nginx/conf.d/default.conf

# Copy your custom Nginx configuration file into the container
# The path './nginx/nginx.conf' is relative to the build context defined in docker-compose.yml
COPY ./nginx/nginx_backend.conf /etc/nginx/nginx.conf

# Expose the port Nginx is configured to listen on
EXPOSE 80
# EXPOSE 443 # If using HTTPS

# Command to run Nginx (default command for Nginx image is usually sufficient)
CMD ["nginx", "-g", "daemon off;"]